### ISSUE TITLE
Height/Width issue when inside tab

### ISSUE THREAD

**Issue by jscarle** [gitbrent/bootstrap4-toggle#26] opened 2019-12-19 00:00 UTC
When placing checkboxes inside a tab, the width and height become 0px.

![Capture](https://user-images.githubusercontent.com/29762210/71133442-a42fe700-21c8-11ea-8d2d-3a8b5db85b32.PNG)

**Comment by esyriani** [comment] 2020-01-07 12:39
I have the same problem. Is there a quick fix?

**Comment by casually-creative** [comment] 2020-01-10 11:19
Experiencing the same. I placed the toggle button inside a bootstrap dropdown menu, and the width becomes 0px. For comparison I placed it in a high level element, and it worked perfectly. I've double checked and there's none of my custom css in effect. It seems like the script that dynamically sets the width and height in pixels, is just not working in some scenarios.

**Comment by gitbrent** [comment] 2020-02-04 03:36
Duplicate of Issue #15 

The next release will prevent controls from being `0px`

**Comment by vincentasakura-ms** [comment] 2020-03-09 07:54
The width problem also occurs on hidden Bootstrap tabs. The < label > elements become too short and the text inside it gets cut off.

**Comment by vincentasakura-ms** [comment] 2020-03-10 08:03
Update: As some kind of workaround I applied some custom CSS on my Bootstrap tabs when they're hidden. Inspired by https://stackoverflow.com/a/23267110, I added this CSS

```
.tab-content.width-fix > .tab-pane:not(.active),
.pill-content.width-fix > .pill-pane:not(.active)
{
    display: block;
    height: 0;
    overflow-y: hidden;
}
```
and added the class "width-fix" to my tab-content `<div>`, thus:
```
<div class="tab-content width-fix">
    <div class="tab-pane">... [toggles somewhere here] ...</div>
    ...
</div>
```
This way, the CSS fix only applies to elements I explicitly want to render differently in that regard.

**Comment by deltemp** [comment] 2020-05-22 19:10
My workaround was to copy the width and height values from  somewhere else, where it worked, and put it on the DOM ready event, like below:

`$(document).ready(function(){
      $('[data-toggle="toggle"]').css({'width':'73.3359px', 'height':'38px'});
});`

I know that's not ideal, but it worked!

**Comment by mashedkeyboard** [comment] 2020-06-26 17:38
Hi @gitbrent, hope you're okay, and thanks for maintaining this amazing library :)

Do you know when the next release will be - and/or any ideas as to how we could help get this issue resolved? Happy to sort out a PR myself if it'd be convenient, but I'd need to root around to find where the actual problem is, so if you know already, any pointers would be appreciated :D

Cheers!

**Comment by meduzapat** [comment] 2020-09-22 02:35
my temporary fix until the issue is  fixed:
```css
#myTabs .toggle.btn-sm {
	min-width: 79.1333px;
	min-height: 31px;
}
```
replace the values to match your needs, also you can use different sizes for different "sections"

**Closed as completed** 2023-09-02 19:33 UTC
Labels: duplicate
